AdminApp/urls.py
from django.urls import path
from AdminApp.views import *
urlpatterns = [
    path('dashboard/', dashboard, name="admin_dashboard"),
    path('booking_list/', booking_list, name="admin_booking_list"),
    path('manage_booking/<int:id>/', manage_booking, name="admin_manage_booking"),
    path('delete_booking/<int:id>/', delete_booking, name="admin_delete_booking"),
    path('upload_ticket/', upload_ticket, name="admin_upload_ticket"),
    path('event_list/', event_list, name="admin_event_list"),
    path('comitee_year_list/', comitee_year_list, name="admin_comitee_year_list"),
    path('update_comitee_year/', update_comitee_year, name="admin_update_comitee_year"),
    path('delete_comitee_year/<int:id>', delete_comitee_year, name="admin_delete_comitee_year"),
    path('comitee_member_list/', comitee_member_list, name="admin_comitee_member_list"),
    path('update_comitee_member/', update_comitee_member, name="admin_update_comitee_member"),
    path('delete_comitee_member/<int:id>', delete_comitee_member, name="admin_delete_comitee_member"),

    path('create_event/', create_event, name="create_event"),
    path('update_event/<int:id>', update_event, name="update_event"),
    path('delete_event/<int:id>', delete_event, name="delete_event"),
    path('update_event_publish_status/', update_event_publish_status, name="admin_update_event_publish_status"),
    path('event_details/<int:id>', event_details, name="admin_event_details"),
    path('add_event_ticket_price/', add_event_ticket_price, name="admin_add_event_ticket_price"),
    path('custom_logout/', custom_logout, name="custom_logout"),

    path('delete_event_ticket_price/<int:id>', delete_event_ticket_price, name="admin_delete_event_ticket_price"),
    path('delete_event_brochure/<int:id>', delete_event_brochure, name="admin_delete_event_brochure"),
    path('delete_event_images/<int:id>', delete_event_images, name="admin_delete_event_images"),
    path('create_event_thumbnail/', create_event_thumbnail, name="create_event_thumbnail"),

    path('members_list/', members_list, name="admin_members_list"),
    path('member_details/<int:id>', member_details, name="admin_member_details"),
    path('update_member_profile/<int:id>', update_member_profile, name="admin_update_member_profile"),
    path('delete_member_user/<int:id>', delete_member_user, name="admin_delete_member_user"),

    path('photo_gallery_list/', photo_gallery_list, name="admin_photo_gallery_list"),
    path('create_photo_for_gallery/', create_photo_for_gallery, name="admin_create_photo_for_gallery"),
    path('delete_photo_from_gallery/<int:id>', delete_photo_from_gallery, name="admin_delete_photo_from_gallery"),
    
    path('video_gallery_list/', video_gallery_list, name="admin_video_gallery_list"),
    path('create_video_for_gallery/', create_video_for_gallery, name="admin_create_video_for_gallery"),
    path('delete_video_from_gallery/<int:id>', delete_video_from_gallery, name="admin_delete_video_from_gallery"),

    path('advertisement_list/', advertisement_list, name="admin_advertisement_list"),
    path('create_advertisement/', create_advertisement, name="admin_create_advertisement"),
    path('update_advertisement/', update_advertisement, name="admin_update_advertisement"),
    path('delete_advertisement/<int:id>', delete_advertisement, name="admin_delete_advertisement"),

    path('news_list/', news_list, name='admin_news_list'),
    path('create_news/', create_news, name='admin_create_news'),
    path('update_news/<int:id>/', update_news, name='admin_update_news'),
    path('delete_news/<int:id>/', delete_news, name='admin_delete_news'),
    path('create_news_photos_videos/', create_news_photos_videos, name='admin_create_news_photos_videos'),
    path('news_details/<int:id>/', news_details, name='admin_news_details'),
    path('delete_news_photos/<int:id>/', delete_news_photos, name='admin_delete_news_photos'),
    path('delete_news_video/<int:id>/', delete_news_video, name='admin_delete_news_video'),


]

GYA/urls.py
 
from django.contrib import admin
from django.urls import path,include
from AdminApp.views import register,verify_otp, login_with_otp,user_login,membership_payment
from Website.views import index

from AdminApp import urls as AdminUrls
from  UserApp import urls as UserUrls
from  Website import urls as WebsiteUrls

from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('default_admin/', admin.site.urls),
    path('', index, name='index' ),
    path('admin/', include(AdminUrls)),
    path('user/', include(UserUrls)),
    path('web/', include(WebsiteUrls)),
    path('verify_otp/', verify_otp, name="verify_otp"),
    path('login/', user_login, name="user_login"),
    path('login_otp/', login_with_otp, name="login_with_otp"),
    path('register/', register, name="register"),
    path('membership_payment/', membership_payment, name="membership_payment"),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

AdminApp/models.py
import random
import string
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.utils import timezone
import threading
from django.core.mail import send_mail
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError 
import random


class ComiteeYear(models.Model):
    year=models.CharField(max_length=20)
    def __str__(self):
       return self.year
 

class ComiteeMember(models.Model):
    year=models.ForeignKey(ComiteeYear, on_delete=models.CASCADE)
    image=models.ImageField(upload_to="ComiteeMembers/", height_field=None, width_field=None, max_length=300)
    name=models.CharField(max_length=50)
    position=models.CharField(max_length=50)
    def __str__(self):
       return self.year.year

GENDER = (
    ("Male", "Male"),
    ("Female", "Female")
)

class OTP(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    otp = models.CharField(max_length=6)
    phone_number = models.CharField(max_length=15, null=True,db_index=True)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    member_id = models.CharField(max_length=20, null=True,default=0)
    dob = models.DateField(auto_now=False, auto_now_add=False)
    gender = models.CharField(max_length=50, choices=GENDER, null=True)
    is_member = models.BooleanField(default=False)
    paid_date = models.DateTimeField(auto_now=False, auto_now_add=False, null=True)
    registration_date = models.DateTimeField(auto_now=False, auto_now_add=True, null=True)

    def save(self, *args, **kwargs):
        if not self.member_id:
            last_member = UserProfile.objects.all().order_by('-member_id').first()
            if last_member.member_id:
                last_number = int(last_member.member_id.split('MBR')[1])
                new_number = last_number + 1
            else:
                new_number = 201
            self.member_id = f'MBR{new_number}'
        super().save(*args, **kwargs)

RELATION = (
    ("Self", "Self"),
    ("Mother", "Mother"),
    ("Father", "Father"),
    ("Son", "Son"),
    ("Daughter", "Daughter"),
    ("Brother", "Brother"),
    ("Sister", "Sister"),
    ("Grandfather", "Grandfather"),
    ("Grandmother", "Grandmother"),
    ("Grandson", "Grandson"),
    ("Granddaughter", "Granddaughter"),
    ("Uncle", "Uncle"),
    ("Aunt", "Aunt"),
    ("Nephew", "Nephew"),
    ("Niece", "Niece"),
    ("Cousin", "Cousin"),
)

class Guest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=100)
    gender = models.CharField(max_length=50, choices=GENDER)
    dob = models.DateField(auto_now_add=False,auto_now=False)
    relation = models.CharField(max_length=50, choices=RELATION)
    phone_number = models.CharField(max_length=50)
 
    def __str__(self):
        return self.full_name

class Event(models.Model):
    STATUS_CHOICES = (
        ('upcoming', 'Upcoming '),
        ('active', 'Active'),
        ('completed', 'Completed'),
        ('canceled', 'Canceled'),
    )
    title = models.CharField(max_length=200)
    description = models.TextField()
    location = models.CharField(max_length=300)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    organizer =  models.CharField(max_length=100)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='upcoming')
    url = models.URLField(blank=True, null=True)
    ticket_price = models.IntegerField(default=0)
    is_publish=models.BooleanField(default=False)


    def __str__(self):
        return self.title


class EventTicketPrice(models.Model):
    event=models.ForeignKey(Event, on_delete=models.CASCADE,null=True)
    member_price=models.IntegerField(default=0)
    guest_price=models.IntegerField(default=0)
    def __str__(self):
        return f"{self.event.title} Ticket Price"

class Ticket(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE,null=True)
    ticket_id=models.CharField(max_length=50)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    is_paid=models.BooleanField(default=False)
    booking_date=models.DateTimeField(auto_now_add=True)
    ticket_file=models.FileField(upload_to="Tickets/", max_length=1000,null=True,blank=True)
    paid_amount=models.IntegerField(default=0)

    class Meta:
        ordering = ['-booking_date']

    def __str__(self):
        return f"{self.event.title} Ticket"
    
    def save(self, *args, **kwargs):
        if not self.ticket_id:
            # Generate a ticket ID in the format TKT + 11 random digits
            self.ticket_id = 'TKT' + ''.join([str(random.randint(0, 9)) for _ in range(11)])
        super(Ticket, self).save(*args, **kwargs)


class BookingMembers(models.Model):
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    guests=models.ForeignKey(Guest, on_delete=models.CASCADE,null=True,blank=True)
    member=models.ForeignKey(User, on_delete=models.CASCADE,null=True,blank=True) 
    def __str__(self):
        return f"{self.ticket.event.title} Booking Members"


class EventThumbnail(models.Model):
    event = models.OneToOneField("Event", on_delete=models.CASCADE)
    thumbnail = models.ImageField(upload_to="event_thumbnail/", help_text="Recommended Size 1280 x 720 (landscape)", blank=False, null=True)

    def __str__(self):
        return f"{self.event.title} Thumbnail"
    
class EventImagesBrochure(models.Model):
    event = models.ForeignKey("Event", on_delete=models.CASCADE)
    image = models.ImageField(upload_to="event_images/", blank=True, null=True)
    brochure = models.FileField(upload_to="event_brochures/", blank=True, null=True)

    def __str__(self):
        return f"{self.event.title} Image and Brochure"
    


class PhotoGallery(models.Model):
    caption = models.CharField(max_length=255, blank=True, null=True)
    image = models.ImageField(upload_to="photo_gallery/")
    def __str__(self):
        return f"{self.caption} Image"
    

class VideoGallery(models.Model):
    caption = models.CharField(max_length=255, blank=True, null=True)
    video_link = models.CharField(blank=True, null=True, help_text="Enter YouTube video link", max_length=255)

    def __str__(self):
        return f"{self.caption} Image"
    

class Advertisement(models.Model):
    content=models.TextField()
    is_active = models.BooleanField(default=True)
    url=models.URLField(max_length=200, blank=True, null=True)
    def __str__(self):
        return self.content

class News(models.Model):
    title=models.CharField(max_length=200)
    content=models.TextField()
    thumbnail = models.ImageField(upload_to="news_thumbnail/",  help_text="Recommended Size 1280 x 720 (landscape)", blank=True, null=True)
    is_active = models.BooleanField(default=True)
    date=models.DateField(null=True, auto_now=False, auto_now_add=False)
    def __str__(self):
        return self.title
    
class NewsPhotosVideos(models.Model):
    news = models.ForeignKey(News, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="news_photos/", blank=True, null=True)
    video_link = models.CharField(blank=True, null=True, help_text="Enter YouTube video link", max_length=255)
    def __str__(self):
        return f"{self.news.title} Photos and Videos"

    def get_youtube_embed_url(self):
        if self.video_link:
            video_id = self.get_video_id()
            print(video_id)
            return f"https://www.youtube.com/embed/{video_id}"
        return None

    def get_video_id(self):
        if self.video_link:
            return self.video_link.split('v=')[-1]
        return None

    def video_thumbnail(self):
        if self.video_link:
            video_id = self.get_video_id()
            return f"https://img.youtube.com/vi/{video_id}/0.jpg"
        return None

    

AdminApp/templates/admin_advertisements_list.html
{% extends "admin_base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<style>
  
</style>
<main id="main" class="main">
    <div class="pagetitle">
        <h1>Advertisements List</h1>
        <div class="row">
            <div class="col">
            </div>
        </div>
    </div><!-- End Page Title -->

    <div class="row">
        <div class="col-lg-12">
            <div class="row">
                <div class="container" style="max-width:97%;">
                    <div class="text-lg-end text-start">
                        <!-- Use text-lg-end for right alignment in large screens -->
                        <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#create_add"> </i> Create New
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <hr>



     

    <section class="section dashboard">
        <div class="row">

            <!-- Left side columns -->
            <div class="col-lg-12">
                <div style="padding:2%">
                    <!-- Left side columns -->
                    <div>
                        <div class="" style="overflow:scroll;">
                            <table id="example" class="table table-striped"
                                style="overflow:scroll;  width:100%; min-width: max-content;">
                                <thead>
                                    <tr style="background:#02B4C3;">
                                        <th scope="col" class="text-center text-white">Sr.No</th>
                                        <th scope="col" class="text-center text-white">Status</th>
                                        <th scope="col" class="text-center text-white">Content</th>
                                        <th scope="col" class="text-center text-white">URL</th>
                                        <th scope="col" class="text-center text-white">Action</th>
                                   </tr>
                                </thead>
                                <tbody>
                                    {% for add in advertisements %}
                                    <tr>
                                        <td class="text-center">{{ forloop.counter }}</td>
                                        <td class="text-center"> 
                                            {% if add.is_active %}
                                            <span class="badge bg-success">Publish</span>
                                            {% else %}
                                            <span class="badge bg-danger">Not Publish</span>
                                            {% endif %}
                                        </td>
                                        <td class="text-center">{{ add.content }}</td>
                                        <td class="text-center"><a href="{{ add.url }}" target="__blank">Click me</a></td> 
                                        <td  class="text-center">
                                            
                                        <a href="#" class="btn btn-primary mr-2"  data-toggle="modal" data-target="#model_update_add" onclick="update_add('{{add.id}}','{{add.content}}','{{add.url}}','{{add.is_active}}')">
                                            <i class="bi bi-pencil"></i>
                                        </a> 
                                        <a href="{% url "admin_delete_advertisement" add.id %}" class="btn btn-danger" title="Delete">
                                            <i class="bi bi-trash"></i></a>
                                        </td>
                                
                                    </tr>

                                    {% empty %}
                                    <tr>
                                        <td colspan="8" class="text-center">No Record found.</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div><!-- End Left side columns -->


            </div>
        </div><!-- End Left side columns -->

    </section>

    <!-- Add DataTables JavaScript -->
      

</main><!-- End #main -->


<div class="modal fade" id="create_add" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document" style="max-width:1000px;">
        <div class="modal-content">
            <div class="modal-header bg-gradient-primary text-light ">
                <h5 class="modal-title" id="exampleModalLongTitle">Create Advertisement</h5> 
            </div>
            <div class="modal-body">
                <div class="row">
                
                    <form method="post" id="create_add" action="{% url "admin_create_advertisement" %}">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-sm-12">
                                 {{form.content|as_crispy_field}}
                            </div>
                            <div class="col-sm-12">
                                 {{form.url|as_crispy_field}}
                            </div>
                            <div class="col-sm-12">
                                 {{form.is_active|as_crispy_field}}
                            </div>
                              
                        </div>

                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <input type="submit" value="Update"  class="btn bg-gradient-primary text-light"></input>
 
                        </div>
 
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="model_update_add" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document" style="max-width:1000px;">
        <div class="modal-content">
            <div class="modal-header bg-gradient-primary text-light ">
                <h5 class="modal-title" id="exampleModalLongTitle">Update Advertisement</h5> 
            </div>
            <div class="modal-body">
                <div class="row">
                
                    <form method="post" id="update_add" action="{% url "admin_update_advertisement" %}">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-sm-12">
                                 {{form.content|as_crispy_field}}
                            </div>
                            <div class="col-sm-12">
                                 {{form.url|as_crispy_field}}
                            </div>
                            <div class="col-sm-12">
                                 {{form.is_active|as_crispy_field}}
                            </div>
                              
                            <input type="hidden" name="txt_id" id="txt_id">
                        </div>

                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <input type="submit" value="Update"  class="btn bg-gradient-primary text-light"></input>
 
                        </div>
 
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>





<script>
    function update_add(id, content, url,is_active) {
        // Assuming your form has an id attribute set to "product_update_form"
  
        var form = document.getElementById("update_add");
        // Update form elements with the provided values 
        
        var id_val = form.elements["txt_id"];
        id_val.value = id ;
        
        var content_val = form.elements["id_content"];
        content_val.value = content ;
        
        var url_val = form.elements["id_url"];
        url_val.value = url ;
        
        var isActiveField = form.querySelector("input[name='is_active']");
        isActiveField.checked = is_active === 'True' || is_active === true;
    }

 
</script>
 
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" crossorigin="anonymous"></script> 

{% endblock content %}

AdminApp/templates/admin_commitee_year.html
{% extends "admin_base.html" %}
{% load crispy_forms_tags %}
{% block content %} 
<main id="main" class="main">
    <div class="pagetitle">
        <h1>Comitee Year List</h1>
        <div class="row">
            <div class="col">
            </div>
        </div>
    </div><!-- End Page Title -->

    <div class="row">
        <div class="col-lg-12">
            <div class="row">
                <div class="container" style="max-width:97%;">
                    <div class="text-lg-end text-start">
                        <!-- Use text-lg-end for right alignment in large screens -->
                        <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#add_new_year"><i
                                class="mdi mdi-filter"></i> Add New</a> 
                                 
                    </div>
                </div>
            </div>
        </div>
    </div>
    <hr>



    <div class="modal fade" id="add_new_year" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
        aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document" style="max-width:1000px;">
            <div class="modal-content">
                <div class="modal-header bg-gradient-primary text-light ">
                    <h5 class="modal-title" id="exampleModalLongTitle">Create New Event</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <form method="post"
                            enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">
                                {{form|crispy}}
                            </div>
                            <center>
                                <input type="submit" id="btnCreateSubmit" value="Submit"
                                    class="btn bg-gradient-primary text-light"></input>
                            </center>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <section class="section dashboard">
        <div class="row">

            <!-- Left side columns -->
            <div class="col-lg-12">
                <div style="padding:2%">
                    <!-- Left side columns -->
                    <div>
                        <div class="" style="overflow:scroll;">
                            <table id="example" class="table table-striped"
                                style="overflow:scroll;  width:100%; min-width: max-content;">
                                <thead>
                                    <tr style="background:#02B4C3;">
                                        <th scope="col" class="text-center text-white">Sr.No</th>
                                        <th scope="col" class="text-center text-white">Session</th>
                                        <th scope="col" class="text-center text-white">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for i in session %}
                                    <tr>
                                        <td class="text-center">{{ forloop.counter }}</td>
                                        <td class="text-center">{{ i.year }}</td>
                                        <td class="text-center">
                                            <a href="" class="btn btn-primary">Edit</a>
                                            <a href="{% url "admin_delete_comitee_year" i.id %}" class="btn btn-danger">Delete</a>
                                        </td>
                                    </tr>
                                    {% empty %}
                                    <tr>
                                        <td colspan="8" class="text-center">No Session found.</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div><!-- End Left side columns -->


            </div>
        </div><!-- End Left side columns -->

    </section>

    <!-- Add DataTables JavaScript -->
      

</main><!-- End #main -->


{% endblock content %}

AdminApp/templates/admin_update_news.html
{% extends "admin_base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<style>
    #id_content {
        height: 100px;
    } 

    .update_news{
        
        border-radius: 20px;
        background-color: #fff;
    }
     
</style>
<main id="main" class="main">
    <div class="pagetitle">
        <h1>Update Events</h1>
        <div class="row">
            <div class="col">
            </div>
        </div>
    </div><!-- End Page Title -->
   
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-sm-12">
                 
                 <br><br>
                <div class="update_news p-4" id="update_news">
                         
                    <form id="update_news_form"  enctype="multipart/form-data"  method="post">
                        {% csrf_token %} 
                        <div class="row">
                            <div class="col-sm-12">
                                {{form|crispy}}
                            </div>
                             
                            
                        </div>
                        <center>
                        <input type="submit" id="update_form_submit_button" class="btn btn-primary mt-2 px-5" value="Update">

                        <button class="btn btn-secondary mt-2 px-4"  id="update_form_loading_button" type="button" style="display: none;"  disabled>
                            <span class="spinner-grow spinner-grow-sm" role="status" aria-hidden="true"></span>
                            Loading....
                          </button>
                        </center>
                    </form>
                </div>

            </div>
             
        </div>
    </div>
 
    </script>

</main><!-- End #main -->

<script>
    
    function submitUpdateEventForm() {
        document.getElementById('update_form_submit_button').style.display = 'none';
        document.getElementById('update_form_loading_button').style.display = 'block';
        document.getElementById('update_news_form').submit();
    }
</script>
{% endblock content %}

AdminApp/templates/update_event.html
{% extends "admin_base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<style>
    #id_description {
        height: 100px;
    } 

    .update_event{
        
        border-radius: 20px;
        background-color: #fff;
    }
     
</style>
<main id="main" class="main">
    <div class="pagetitle">
        <h1>Update Events</h1>
        <div class="row">
            <div class="col">
            </div>
        </div>
    </div><!-- End Page Title -->
   
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-sm-12">
                 
                 <br><br>
                <div class="update_event p-4" id="update_event">
                         
                    <form id="update_event_form"   onsubmit="submitUpdateEventForm()"   method="post">
                        {% csrf_token %} 
                        <div class="row">
                            <div class="col-sm-12">
                                {{form.title|as_crispy_field}}
                            </div>
                            <div class="col-sm-12">
                                {{form.description|as_crispy_field}}
                            </div>
                            <div class="col-sm-4">
                                {{form.location|as_crispy_field}}
                            </div>
                            <div class="col-sm-4">
                                {{form.start_time|as_crispy_field}}
                            </div>
                            <div class="col-sm-4">
                                {{form.end_time|as_crispy_field}}
                            </div>
                            
                            <div class="col-sm-4">
                                {{form.organizer|as_crispy_field}}
                            </div>
                            <div class="col-sm-4">
                                {{form.status|as_crispy_field}}
                            </div>
                            <div class="col-sm-4">
                                {{form.ticket_price|as_crispy_field}}
                            </div>

                             
                            <div class="col-sm-6">
                                {{form.url|as_crispy_field}}
                            </div>

                            
                        </div>
                        <center>
                        <input type="submit" id="update_form_submit_button" class="btn btn-primary mt-2 px-5" value="Update">

                        <button class="btn btn-secondary mt-2 px-4"  id="update_form_loading_button" type="button" style="display: none;"  disabled>
                            <span class="spinner-grow spinner-grow-sm" role="status" aria-hidden="true"></span>
                            Loading....
                          </button>
                        </center>
                    </form>
                </div>

            </div>
             
        </div>
    </div>
 
    </script>

</main><!-- End #main -->

<script>
    
    function submitUpdateEventForm() {
        document.getElementById('update_form_submit_button').style.display = 'none';
        document.getElementById('update_form_loading_button').style.display = 'block';
        document.getElementById('update_event_form').submit();
    }
</script>
{% endblock content %}